version: '3.8'

services:
  web:
    build: .
    container_name: fujimir_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=file:/app/prisma/db/prod.db
      - NODE_ENV=production
    volumes:
      # Persist uploads
      - ./uploads_data:/app/public/uploads
      # Persist SQLite Database
      - ./db_data:/app/prisma/db
    user: "1001:1001" # Running as nextjs user to match Dockerfile
